pipeline {
    agent {
        label "AGENT-1"
    }
    environment {
        // COURSE = "JENKINS"
        appVersion = ""
        REGION="us-east-1"
        ACC_ID="010666226306"
        PROJECT="roboshop"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    // parameters {
    //     // string(name: 'PERSON', defaultValue: 'Mr Jenkins NEW', description: 'Who should I say hello to?')
    //     // text(name: 'BIOGRAPHY', defaultValue: 'JB', description: 'Enter some information about the person')
    //     // booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
    //     // choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    //     // password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password') 
    // }
    stages {
        stage('init') {
            steps {
                 withAWS(credentials: 'aws-credds', region: 'us-east-1') {
                 sh """
                    cd 00-vpc
                    terraform init -reconfigure
                 """
            }
            }
        }
        stage('plan') {
            steps {
                 withAWS(credentials: 'aws-credds', region: 'us-east-1') {
                 sh """
                    cd 00-vpc
                    terraform plan
                 """
            }
            }
        }
        stage('apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }
            steps {
                 withAWS(credentials: 'aws-credds', region: 'us-east-1') {
                 sh """
                    cd 00-vpc
                    terraform apply -auto-approve
                 """
                }
            }
        }
        stage('Trigger SG') {
            steps {
                script {
                    build job: '10-sg', 
                      propagate: false,  // even SG fails VPC will not be effected
                      wait: false // VPC will not wait for SG pipeline completion
                }
            }
        }
       
        stage('Deploy') {
            // input {
            //     message "Should we continue?"
            //     ok "Yes, we should."
            //     submitter "alice,bob"
            //     parameters {
            //         string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
            //     }
            // }
            steps {
                echo 'Deploying....'
                // echo "Hello, ${PERSON}, nice to meet you."
            }
        }
    }


    post {
        always {
            echo " always hello"
            deleteDir()
        }
        success {
            echo " success hello"
        }
        failure {
            echo " failure hello"
        }
    }
}